@node Overview
@chapter Overview

@command{unstickpixels} tries to unstick stuck pixels.
It does this by rapidly switching between the colours
sRGB(100 %, 0, 0), sRGB(0, 100 %, 0), and sRGB(0, 0, 100 %),
which are displayed on the entire monitor. On all of the
monitors. It helps to massage defective dots.

Running this program for a number of hours, especially if
combined with massaging defective dots, may heal defective
dots. Dead dots (always black) are hard to revive, but stuck
dots are more probable to get fixed.

Dead (always black) pixels are hard to revive, stuck pixels
on the other hand are more probable to get fixed.

@command{unstickpixels} uses the graphics cards' colour lookup
tables to switch the colour displayed on the screen. If your
computers does not supports this, the option @option{-v} may
help, it will use the framebuffer indirectly, via the terminal.
Unless @option{-v} is used, @command{unstickpixels} runs both
in @command{X} and on the Linux VT.

