@node Rationale
@chapter Rationale

Acer/Packard Bell is not willing to repair all defects
on my computer, but at least I can run this for several
hours and try to revive dead pixels. Playing back a
video that is already available on the Internet has
some deficiencies:

@itemize @bullet{}
@item
Requires a graphics card and video player that can play
back the video in full screen mode efficiently.
@item
Requires @command{X} or a video player than can play
video outside @command{X} efficiently.
@item
Requires the video to be downloaded if it was uploaded
on Youtube, because Youtube does not properly support
full screen.
@item
video playback is required per defective monitor.
@end itemize

